services:
  mongodb:
    image: mongo:6.0
    container_name: kindergarten_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: kindergarten_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/kindergarten
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: kindergarten_frontend
    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  mongo_data:
